spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kakaosecurities
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql : false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info


